package com.example.myapplication.Database;

import android.arch.persistence.db.SupportSQLiteDatabase;
import android.arch.persistence.room.Database;
import android.arch.persistence.room.DatabaseConfiguration;
import android.arch.persistence.room.Room;
import android.arch.persistence.room.RoomDatabase;
import android.content.Context;
import android.support.annotation.NonNull;

import com.example.myapplication.Database.Dao.GroceryDao;
import com.example.myapplication.Database.Dao.GroceryListDao;
import com.example.myapplication.Database.Dao.RecipeDao;
import com.example.myapplication.Database.Dao.RecipeItemDao;
import com.example.myapplication.Database.Entities.Grocery;
import com.example.myapplication.Database.Entities.GroceryListEntity;
import com.example.myapplication.Database.Entities.Recipe;
import com.example.myapplication.Database.Entities.RecipeItem;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;

@Database(entities = {Grocery.class, GroceryListEntity.class, Recipe.class, RecipeItem.class}, version = 1)
public abstract class AppDatabase extends RoomDatabase {
    public abstract GroceryDao groceryDao();
    public abstract GroceryListDao groceryListDao();
    public abstract RecipeDao recipeDao();
    public abstract RecipeItemDao recipeItemDao();

    public static AppDatabase instance = null;

    public static AppDatabase getInstance(final Context context) {
        if (instance == null) {
            synchronized (AppDatabase.class) {
                if (instance == null) {
                    instance = Room.databaseBuilder(context,
                            AppDatabase.class, "database-name").allowMainThreadQueries().build();
                }
            }
        }
        return instance;
    }


    @Override
    public void init(@NonNull DatabaseConfiguration configuration) {
        super.init(configuration);
    }

    public static Grocery[] populate(){
        return new Grocery[]{
                new Grocery("A38, acidophilus tykmælk",false),
//                new Grocery("Ab-mælk, syrnet sødmælk",false),
                new Grocery("Abrikos, konserves, let sukkerlage",false),
                new Grocery("Abrikos, rå",false),
                new Grocery("Abrikosmarmelade",false),
                new Grocery("Agurk, syltet",false),
                new Grocery("Ananas, konserves",false),
                new Grocery("Ananasjuice, konserves",false),
                new Grocery("And, brystkød, rå",false),
                new Grocery("And, kød, rå",false),
                new Grocery("Appelsin, rå",false),
                new Grocery("Appelsinmarmelade",false),
                new Grocery("Asier, syltede",false),
                new Grocery("Asparges, hvide, rå",false),
                new Grocery("Asparges, uspec., rå",false),
                new Grocery("Avocado, rå",false),
                new Grocery("Babymajs, rå",false),
                new Grocery("Bacon, kogestykke, rå",false),
                new Grocery("Bagegær, presset, rå",false),
                new Grocery("Baked beans i tomatsovs, konserves",false),
                new Grocery("Bambusskud, konserves, usaltet",false),
                new Grocery("Banan, rå",false),
                new Grocery("Bayonneskinke, udbenet",false),
                new Grocery("Bitter, Gammel Dansk Bitter Dram",false),
                new Grocery("Bitter, krabask bitter",false),
                new Grocery("Bitter, uspec.",false),
                new Grocery("Bladselleri, rå",false),
                new Grocery("Blomkål, dansk, rå",false),
                new Grocery("Blomkål, importeret, rå",false),
                new Grocery("Blomme, rå",false),
                new Grocery("Blåbær, frosne, usukrede",false),
                new Grocery("Blåmusling, kogt",false),
                new Grocery("Boghvedegryn, rå",false),
                new Grocery("Bolcher, blandede",false),
                new Grocery("Bondebrød med fedtrige frø, industrifremstillet",false),
                new Grocery("Bouillon, hønsekød, spiseklar",false),
                new Grocery("Bouillon, oksekød, terning, spiseklar",false),
                new Grocery("Brie, 45+",false),
                new Grocery("Brie, 60+",false),
                new Grocery("Brisling (sardin), i olie, konserves",false),
                new Grocery("Brisling, rå",false),
                new Grocery("Broccoli, kogt",false),
                new Grocery("Brombær, dybfrost, usukrede",false),
                new Grocery("Brombær, syltede",false),
                new Grocery("Brune bønner, tørrede, rå",false),
                new Grocery("Brøndkarse, rå",false),
                new Grocery("Bulgur (hvedekerner, knækkede, parboiled), rå",false),
                new Grocery("Burger med bøf og ost, salat og dressing, fastfood",false),
                new Grocery("Burger med kylling, salat og dressing, fastfood",false),
                new Grocery("Burger med medium bøf, salat og dressing, fastfood",false),
                new Grocery("Byggryn, rå",false),
                new Grocery("Bækforel, filet, røget",false),
                new Grocery("Bøfsandwich med salat og dressing, fastfood",false),
                new Grocery("Bønnespirer, mung, rå",false),
                new Grocery("Bønnespirer, uspec., rå",false),
                new Grocery("Cacaomælk",false),
                new Grocery("Cacaoskummetmælk",false),
                new Grocery("Cacaosmør",false),
                new Grocery("Camembert, 45+",false),
                new Grocery("Campari",false),
                new Grocery("Carambol, bilimbing, stjernefrugt, rå",false),
                new Grocery("Cashewnød, tørristet",false),
                new Grocery("Champignon, konserves",false),
                new Grocery("Cheddar, 50+",false),
                new Grocery("Chesire, 50+",false),
                new Grocery("Chokolade, fløde, med nødder",false),
                new Grocery("Chokolade, mørk",false),
                new Grocery("Citronsaft, friskpresset",false),
                new Grocery("Cognac",false),
                new Grocery("Cornflakes, uspec.",false),
                new Grocery("Creme fraiche 38 %",false),
                new Grocery("Creme fraiche 9 %",false),
                new Grocery("Cultura, syrnet sødmælk (HISTORISK)",false),
                new Grocery("Daddel, tørret",false),
                new Grocery("Danablu 60+",false),
                new Grocery("Danbo, 30+",false),
                new Grocery("Dild, rå",false),
                new Grocery("Dragé, lakrids",false),
                new Grocery("Dressing, blue cheese",false),
                new Grocery("Dressing, creme fraiche, kalorielet",false),
                new Grocery("Dressing, italiensk",false),
                new Grocery("Dressing, mayonnaise, kalorielet",false),
                new Grocery("Dressing, olie-eddike, kalorielet",false),
                new Grocery("Drueagurk (sylteagurk), rå",false),
                new Grocery("Due, vildt, kød og skind, rå",false),
                new Grocery("Dürumrulle med kebab, salat og dressing, fastfood",false),
                new Grocery("Eddike",false),
                new Grocery("Emmentaler, 45+",false),
                new Grocery("Esrom, 60+",false),
                new Grocery("Fasan, kød og skind, rå",false),
                new Grocery("Fennikel, frø",false),
                new Grocery("Fersken, konserves",false),
                new Grocery("Fersken, tørret",false),
                new Grocery("Feta, 50+",false),
                new Grocery("Figen, tørret",false),
                new Grocery("Fiskefars, rå",false),
                new Grocery("Fiskefilet, paneret, stegt, delikatesse",false),
                new Grocery("Fiskeolie, hydrogeneret",false),
                new Grocery("Flûte med fedtrige frø, industrifremstillet",false),
                new Grocery("Flûte, groft, industrifremstillet",false),
                new Grocery("Fløde 13 %",false),
                new Grocery("Fløde 18 %",false),
                new Grocery("Fløde 50 %",false),
                new Grocery("Fløde 9 %, syrnet",false),
                new Grocery("Flødeis",false),
                new Grocery("Flødeost, 70+",false),
                new Grocery("Flødeskumskage, jordbærkage",false),
                new Grocery("Flødeskumskage, lagkagesnitte",false),
                new Grocery("Flødeskumskage, napoleonskage",false),
                new Grocery("Flødeskumskage, walesbolle/-kringle",false),
                new Grocery("Forloren skildpadde, uspec.",false),
                new Grocery("Forårsrulle, dybfrost",false),
                new Grocery("Fransk hot dog, fastfood",false),
                new Grocery("Frikadelle, stegt, industrifremstillet",false),
                new Grocery("Frugtpålæg, figen",false),
                new Grocery("Frugtsaft, blandet, sødet, koncentreret",false),
                new Grocery("Fruktose",false),
                new Grocery("Fynbo, 45+",false),
                new Grocery("Fårekød, kølle, rå",false),
                new Grocery("Gaffelbidder",false),
                new Grocery("Gedemælk",false),
                new Grocery("Gin",false),
                new Grocery("Grahamsmel, fuldkornshvedemel",false),
                new Grocery("Granatæble, punisk æble, råt",false),
                new Grocery("Grapefrugtjuice, konserves, usødet",false),
                new Grocery("Grisebryst, kogestykke med svær, rå",false),
                new Grocery("Grisebryst, slag, rullesteg, råt",false),
                new Grocery("Grisebryst, stegestykke, uden svær, ca. 2 mm spæk, rå",false),
                new Grocery("Grisefedt, afsmeltet, Raffinol",false),
                new Grocery("Grisefilet, røget, pålæg",false),
                new Grocery("Grisekød i karrysovs, dybfrost",false),
                new Grocery("Grisekød, bryst med svær, rå",false),
                new Grocery("Grisekød, hakket, 10-15% fedt, råt",false),
                new Grocery("Grisekød, hakket, 5-10% fedt, råt",false),
                new Grocery("Grisekød, mellemkam med svær, rå",false),
                new Grocery("Grisekød, nakkekam med svær, rå",false),
                new Grocery("Grisekød, uspec., ca. 10 % fedt, råt",false),
                new Grocery("Grisekød, uspec., fedt, råt",false),
                new Grocery("Grisemørbrad, afpudset, rå",false),
                new Grocery("Grovfranskbrød",false),
                new Grocery("Græskar, konserves",false),
                new Grocery("Grønkål, dybfrost",false),
                new Grocery("Grønkål, rå",false),
                new Grocery("Grønne bønner, konserves",false),
                new Grocery("Grønne ærter, dybfrost",false),
                new Grocery("Grønne ærter, rå",false),
                new Grocery("Guavabær, guajavabær, rå",false),
                new Grocery("Gulerod, dansk, rå",false),
                new Grocery("Gulerod, importeret, rå",false),
                new Grocery("Gulerod, konserves",false),
                new Grocery("Gær, tørret",false),
                new Grocery("Gås, kød og skind, rå",false),
                new Grocery("Gåsefedt",false),
                new Grocery("Hajmalle, rå, dybfrost",false),
                new Grocery("Hamburgerryg, røget",false),
                new Grocery("Hasselnød, tørret",false),
                new Grocery("Havarti, 45+",false),
                new Grocery("Havkat, plettet, rå",false),
                new Grocery("Havredrik, ikke beriget",false),
                new Grocery("Havregryn, beriget",false),
                new Grocery("Havregryn, uspec.",false),
                new Grocery("Havtorn, rå",false),
                new Grocery("Hellefisk, røget",false),
                new Grocery("Helleflynder, røget",false),
                new Grocery("Helt, rå",false),
                new Grocery("Hindbær, dybfrost, rå",false),
                new Grocery("Hindbærmarmelade",false),
                new Grocery("Hindbærsaft, sød, koncentreret",false),
                new Grocery("Hirseflager",false),
                new Grocery("Hjerte, høne (kylling), råt",false),
                new Grocery("Hjerte, okse, råt",false),
                new Grocery("Honningmelon, rå",false),
                new Grocery("Hot dog, almindelig, fastfood",false),
                new Grocery("Hummer, konserves",false),
                new Grocery("Hvalkød, råt",false),
                new Grocery("Hvedebrød, bolle, fin, industrifremstillet",false),
                new Grocery("Hvedebrød, bolle, grov, med fedtrige frø, industrifremstillet",false),
                new Grocery("Hvedebrød, bolle, italiensk type, industrifremstillet",false),
                new Grocery("Hvedebrød, fint, store, industrifremstillet",false),
                new Grocery("Hvedebrød, groft, kærnebrød",false),
                new Grocery("Hvedebrød, groft, store, detailbageri",false),
                new Grocery("Hvedebrød, italiensk type, stort, detailbageri",false),
                new Grocery("Hvedebrød, kastanjebrød",false),
                new Grocery("Hvedebrød, sandwich/toastbrød med fedtrige frø, industrifremstillet",false),
                new Grocery("Hvedebrød, toastbrød, fint, industrifremstillet",false),
                new Grocery("Hvedebrød, trekornsbrød",false),
                new Grocery("Hvedegryn, mannagryn",false),
                new Grocery("Hvedekim, rå",false),
                new Grocery("Hvedeklid",false),
                new Grocery("Hvedemel, bagerimel",false),
                new Grocery("Hvid hvede brød, groft, store, detailbageri",false),
                new Grocery("Hvid hvede, melmix",false),
                new Grocery("Hvidkål, rå",false),
                new Grocery("Hvidløg, tørret, pulver",false),
                new Grocery("Hvidvin, mousserende, champagne",false),
                new Grocery("Hvidvin, sød",false),
                new Grocery("Hvidvin, uden alkohol",false),
                new Grocery("Hvilling, rå",false),
                new Grocery("Hyben, rå",false),
                new Grocery("Hyldebær, rå",false),
                new Grocery("Hyldebærsaft, sød, koncentreret",false),
                new Grocery("Hytteost, 5+",false),
                new Grocery("Høne, kød, rå",false),
                new Grocery("Hørfrøolie",false),
                new Grocery("Ingefær, rod, rå",false),
                new Grocery("Ising, rå",false),
                new Grocery("Ispind, limonade",false),
                new Grocery("Ispind, vanille med chokoladeovertræk",false),
                new Grocery("Jagtpølse, pålæg",false),
                new Grocery("Jordbær i sukkerlage, konserves",false),
                new Grocery("Jordbær, dybfrost, usukrede",false),
                new Grocery("Jordbær, syltede",false),
                new Grocery("Jordbærsaft, sur, koncentreret",false),
                new Grocery("Jordnød, tørret",false),
                new Grocery("Jordnøddesmør",false),
                new Grocery("Julesalat, rå",false),
                new Grocery("Kaffe, drikkeklar",false),
                new Grocery("Kaffe, instant, decaffeinated, pulver",false),
                new Grocery("Kaffe, instant, pulver",false),
                new Grocery("Kage, trøffelprodukt / koldprodukt, industrifremstillet",false),
                new Grocery("Kakao, instant, uden mælk, pulver",false),
                new Grocery("Kakifrugt (Sharon), rå",false),
                new Grocery("Kalkun, bryst (filet), kogt/røget, pålæg",false),
                new Grocery("Kalkun, kød, rå",false),
                new Grocery("Kalkunkød, hakket, 5-10% fedt, råt",false),
                new Grocery("Kalvekød, fedt, råt",false),
                new Grocery("Kalvekød, magert, råt",false),
                new Grocery("Kammerjunkere",false),
                new Grocery("Kanin, kød, rå",false),
                new Grocery("Karameller, blandede",false),
                new Grocery("Karse, frisk",false),
                new Grocery("Kartoffel, chips, fedtreducerede",false),
                new Grocery("Kartoffel, gammel (februar - juni), rå",false),
                new Grocery("Kartoffel, konserves",false),
                new Grocery("Kartoffel, uspec., rå",false),
                new Grocery("Kartoffelmel",false),
                new Grocery("Kartoffelmos, pulver uden tørmælk",false),
                new Grocery("Kaviar, uægte (lodderogn)",false),
                new Grocery("Kebabmix med pommes frites, friturestegt, fastfood",false),
                new Grocery("Kiks til ost, Cream Crackers",false),
                new Grocery("Kiks, fuldkorns-, digestivetype",false),
                new Grocery("Kiks, havre, søde",false),
                new Grocery("Kiks, hvede, sød, med tyk chokolade",false),
                new Grocery("Kiks, rug",false),
                new Grocery("Kinakål, pe-tsai, rå",false),
                new Grocery("Kippers i olie, konserves",false),
                new Grocery("Kirsebær, syltede",false),
                new Grocery("Kirsebærsaft, sur, koncentreret",false),
                new Grocery("Kiwi, rå",false),
                new Grocery("Klipfisk, rå",false),
                new Grocery("Knudekål, glaskål, rå",false),
                new Grocery("Knækbrød, hvede-, fint",false),
                new Grocery("Knækbrød, rug-, fint",false),
                new Grocery("Kogt oksebryst, pålæg",false),
                new Grocery("Kokosmel",false),
                new Grocery("Koldskål",false),
                new Grocery("Konfektureprodukt, skumvare, uspec.",false),
                new Grocery("Koriander, blade, friske",false),
                new Grocery("Koriander, frø",false),
                new Grocery("Krabbekløer, konserves",false),
                new Grocery("Kransekage o.l., industrifremstillet",false),
                new Grocery("Krydder",false),
                new Grocery("Kråse, kylling, rå",false),
                new Grocery("Kuller, rå",false),
                new Grocery("Kumquat, guldorange, dværgappelsin, rå",false),
                new Grocery("Kvark, 5+",false),
                new Grocery("Kylling, ben, kød og skind, rå",false),
                new Grocery("Kylling, bryst, kød og skind, rå",false),
                new Grocery("Kylling, grillstegt, fastfood",false),
                new Grocery("Kylling, kød og skind, friturestegt",false),
                new Grocery("Kylling, kød og skind, paneret, friturestegt",false),
                new Grocery("Kylling, kød, rå",false),
                new Grocery("Kylling, vinge, kød og skind, rå",false),
                new Grocery("Kyllingepølse, pålæg",false),
                new Grocery("Kærnemælk med citronsaft",false),
                new Grocery("Kødboller, konserves",false),
                new Grocery("Kødextrakt, terning",false),
                new Grocery("Kødpølse, pålæg",false),
                new Grocery("Kørvel, hakket, dybfrost",false),
                new Grocery("Kålrabi (kålroe), rå",false),
                new Grocery("Lactose, pulver",false),
                new Grocery("Lakrids, sød",false),
                new Grocery("Lakridskonfekt",false),
                new Grocery("Laks, atlantisk, opdræt, koldrøget",false),
                new Grocery("Laks, atlantisk, opdræt, varmrøget",false),
                new Grocery("Laks, atlantisk, vild, koldrøget",false),
                new Grocery("Laks, atlantisk, vild, rå",false),
                new Grocery("Laks, Stillehavs-, vild, rå",false),
                new Grocery("Lammekød, bov, rå",false),
                new Grocery("Lammekød, kølle, afpudset, rå",false),
                new Grocery("Lammekød, kølle, uspec., rå",false),
                new Grocery("Lammekød, slag, råt",false),
                new Grocery("Lange, filet, rå",false),
                new Grocery("Letmælk, økologisk",false),
                new Grocery("Lever, ande, rå",false),
                new Grocery("Lever, gris, rå",false),
                new Grocery("Lever, kylling, rå",false),
                new Grocery("Leverpostej",false),
                new Grocery("Leverpølse, kalv, pålæg",false),
                new Grocery("Levertran (Sej)",false),
                new Grocery("Likør, kaffe",false),
                new Grocery("Likør, uspec.",false),
                new Grocery("Linser, tørrede, rå",false),
                new Grocery("Litchi, lichiblomme, kinesisk blomme, rå",false),
                new Grocery("Loquat, japansk mispel, rå",false),
                new Grocery("Lucernespirer, rå",false),
                new Grocery("Læskedrik (light), koncentreret (1+10), uden tilsat sukker, uspec.",false),
                new Grocery("Løg, hakkede, dybfrost",false),
                new Grocery("Løg, rå",false),
                new Grocery("Madeira",false),
                new Grocery("Majs, kerner, dybfrost",false),
                new Grocery("Majskolbe, rå",false),
                new Grocery("Majsolie",false),
                new Grocery("Makaroni, spaghetti, fuldkorns-, rå",false),
                new Grocery("Makrel, filet, naturel, konserves",false),
                new Grocery("Makrel, rå",false),
                new Grocery("Mandarin, konserves",false),
                new Grocery("Mandel, rå",false),
                new Grocery("Mangofrugt, mangoblomme, mangga, rå",false),
                new Grocery("Maniok, kassava, rå",false),
                new Grocery("Marcipanprodukt, m/chokolade, uspec.",false),
                new Grocery("Margarine, 80 %, bordbrug, animalsk og vegetabilsk fedt",false),
                new Grocery("Margarine, 80 %, bordbrug, vegetabilsk fedt",false),
                new Grocery("Margarine, 80 %, stegning/bagning, vegetabilsk fedt",false),
                new Grocery("Maribo, 30+",false),
                new Grocery("Marmelade, engelsk type",false),
                new Grocery("Mayonnaise",false),
                new Grocery("Medisterpølse, røget",false),
                new Grocery("Melbanan, grønsagsbanan, plantain, rå",false),
                new Grocery("Melboller, uspec.",false),
                new Grocery("Millionbøf, uspec.",false),
                new Grocery("Minarine, 40 %, vegetabilsk fedt",false),
                new Grocery("Mineralvand, dansk vand o.lign.",false),
                new Grocery("Mineralvand, sodavand, uden tilsat sukker, uspec.",false),
                new Grocery("Miso, sojapasta",false),
                new Grocery("Modermælk, moden",false),
                new Grocery("Morgenmadsprodukt, Guldkorn",false),
                new Grocery("Morgenmadsprodukt, Rice Krispies",false),
                new Grocery("Mozzarella, 45+",false),
                new Grocery("Muskatnød, hel",false),
                new Grocery("Musling, konserves",false),
                new Grocery("Myseost, 33+",false),
                new Grocery("Müsli uden tilsat sukker.",false),
                new Grocery("Müslibar",false),
                new Grocery("Mælkeis, uspec.",false),
                new Grocery("Nektarin, rå",false),
                new Grocery("Nougat",false),
                new Grocery("Nyre, gris, rå",false),
                new Grocery("Nyre, okse, rå",false),
                new Grocery("Okra, gumbo, rå",false),
                new Grocery("Oksekød, entrecote med kappe, rå",false),
                new Grocery("Oksekød, hakket, 15-20% fedt, råt",false),
                new Grocery("Oksekød, højrebsfilet med kappe, rå",false),
                new Grocery("Oksekød, inderlår med kappe, rå",false),
                new Grocery("Oksekød, klump uden kappe, rå",false),
                new Grocery("Oksekød, mellemskært, råt",false),
                new Grocery("Oksekød, skank (osso buco), rå",false),
                new Grocery("Oksekød, spidsbryst, råt",false),
                new Grocery("Oksekød, tykbov (marvpibebov), rå",false),
                new Grocery("Oksekød, tykkam, rå",false),
                new Grocery("Oksekød, tykstegsfilet uden kappe, rå",false),
                new Grocery("Oksekød, tyndbryst, råt",false),
                new Grocery("Oksekød, tyndstegsfilet med fedtkant, rå",false),
                new Grocery("Oksekød, uspec., helt magert, råt",false),
                new Grocery("Oksekød, uspec., middelfedt, råt",false),
                new Grocery("Oksetalg",false),
                new Grocery("Oliven, sorte, saltede, i olie",false),
                new Grocery("Olivenolie",false),
                new Grocery("Ost, fast, 20+, alle typer",false),
                new Grocery("Ost, fast, 40+, alle typer",false),
                new Grocery("Paksoi, pak-choi, pai tsai, rå",false),
                new Grocery("Palmeolie",false),
                new Grocery("Paradisæble, råt",false),
                new Grocery("Parmesan, 32+",false),
                new Grocery("Passionsfrugt, grenadil, rå",false),
                new Grocery("Pasta, rå",false),
                new Grocery("Pastiller, sukkerfri, uspec.",false),
                new Grocery("Paté, pålæg",false),
                new Grocery("Peber, chili, konserves",false),
                new Grocery("Peber, hvid",false),
                new Grocery("Peberfrugt, grøn, rå",false),
                new Grocery("Peberfrugt, rød, rå",false),
                new Grocery("Pecannød, tørret",false),
                new Grocery("Pekannød, olieristet",false),
                new Grocery("Persillerod, rå",false),
                new Grocery("Pinjefrø, tørrede",false),
                new Grocery("Pistacienød, tørristet",false),
                new Grocery("Pitasandwich med kebab, salat og dressing, fastfood",false),
                new Grocery("Pitasandwich med rejer, salat og dressing, fastfood",false),
                new Grocery("Pizza med broccoli, dybfrost",false),
                new Grocery("Pizza med grønt og frugt, tomat og ost, fastfood",false),
                new Grocery("Pizza med kød, tomat og ost, fastfood",false),
                new Grocery("Pizza med tomat og ost, fastfood",false),
                new Grocery("Pizza napolitana, dybfrost",false),
                new Grocery("Pizza, dybfrost, uspec.",false),
                new Grocery("Pommes frites, friturestegt, fastfood",false),
                new Grocery("Pop corn, mikroovn",false),
                new Grocery("Porre, rå",false),
                new Grocery("Poulard, kød og skind, rå",false),
                new Grocery("Purløg, rå",false),
                new Grocery("Pære, rå",false),
                new Grocery("Pølse, bierwurst",false),
                new Grocery("Pølse, cervelatpølse, pålæg",false),
                new Grocery("Pølse, tepølse",false),
                new Grocery("Pølsemix med pommes frites, fastfood",false),
                new Grocery("Quinoa, rå",false),
                new Grocery("Rabarber, dybfrost",false),
                new Grocery("Radise, rå",false),
                new Grocery("Rasp",false),
                new Grocery("Reje, dybvands-, kogt, dybfrost",false),
                new Grocery("Reje, dybvands, kogt, i lage",false),
                new Grocery("Reje, sort tiger-, opdræt, rå, dybfrost",false),
                new Grocery("Remoulade, uspec.",false),
                new Grocery("Ribs, rå",false),
                new Grocery("Ribssaft, sur, koncentreret",false),
                new Grocery("Ris, brune, rå",false),
                new Grocery("Ris, polerede, rå",false),
                new Grocery("Risdrik, tilsat calcium",false),
                new Grocery("Risengryn, grødris, polerede, rå",false),
                new Grocery("Rismel",false),
                new Grocery("Roastbeef, pålæg",false),
                new Grocery("Roquefort, 50+",false),
                new Grocery("Rosenkål, efterår (oktober til december), rå",false),
                new Grocery("Rosenkål, vinter (januar til april), rå",false),
                new Grocery("Rosin uden kerner",false),
                new Grocery("Roulade, hindbær-",false),
                new Grocery("Rugbrød med fedtrige frø og kerner, industrifremstillet",false),
                new Grocery("Rugbrød, fuldkorn, industrifremstillet",false),
                new Grocery("Rugbrød, kun groft rugmel, med fedtrige frø, detailbageri",false),
                new Grocery("Rugbrød, lyst",false),
                new Grocery("Rugbrød, med sigtet mel (soft) og fedtrige frø, industrifremstillet",false),
                new Grocery("Rugbrød, revet, med brunt sukker, uspec.",false),
                new Grocery("Rugkerner, hele/knækkede",false),
                new Grocery("Rugmel, halvsigtet (udmalingsgrad ca. 85 %)",false),
                new Grocery("Rullepølse, lammekød, pålæg",false),
                new Grocery("Rundstykke",false),
                new Grocery("Rygeost, 1 % fedt",false),
                new Grocery("Rype, kød, rå",false),
                new Grocery("Rødbede, konserves",false),
                new Grocery("Rødbede, rå",false),
                new Grocery("Rødfisk, lille, filet, rå",false),
                new Grocery("Rødkål, konserves",false),
                new Grocery("Rødkål, rå",false),
                new Grocery("Rødspætte, filet, paneret, friturestegt",false),
                new Grocery("Rødtunge, rå",false),
                new Grocery("Rødvin, spansk, sød",false),
                new Grocery("Saccharin",false),
                new Grocery("Salami",false),
                new Grocery("Salat, endivie, bredbladet (escarole), rå",false),
                new Grocery("Salat, hovedsalat, rå",false),
                new Grocery("Salat, mayonnaise-, italiensk",false),
                new Grocery("Salat, mayonnaise-, makrel-",false),
                new Grocery("Salat, Romaine, romersk, rå",false),
                new Grocery("Salt, bordsalt (jodberiget)",false),
                new Grocery("Salt, havsalt (jodberiget)",false),
                new Grocery("Samsø, 30+",false),
                new Grocery("Sandart, rå",false),
                new Grocery("Sandwich med frikadelle, salat og dressing, fastfood",false),
                new Grocery("Sandwich med kylling og bacon, salat og dressing, fastfood",false),
                new Grocery("Sandwich med ribbenssteg, rødkål og agurk, fastfood",false),
                new Grocery("Sandwich med skinke og ost, toasted, fastfood",false),
                new Grocery("Sapodille (chiku), rå",false),
                new Grocery("Sardin, i olie, konserves",false),
                new Grocery("Sauce, barbeque",false),
                new Grocery("Savoykål, rå",false),
                new Grocery("Selleri, blade, rå",false),
                new Grocery("Sennep, brun, færdiglavet",false),
                new Grocery("Sesamfrø, afskallede",false),
                new Grocery("Sesamolie",false),
                new Grocery("Sherry, sød",false),
                new Grocery("Sigtebrød",false),
                new Grocery("Sild, høstsild, fedsild, rå",false),
                new Grocery("Sild, marineret, i karrysauce",false),
                new Grocery("Sild, marineret, kryddersild",false),
                new Grocery("Sild, røget",false),
                new Grocery("Sild, Østersø, uspecificeret, rå",false),
                new Grocery("Sirup",false),
                new Grocery("Skinke, kogt, konserves",false),
                new Grocery("Skinke, røget",false),
                new Grocery("Skinke, yderlår, helt afpudset, råt",false),
                new Grocery("Skinkemignon (lårtunge), helt afpudset, rå",false),
                new Grocery("Skorzonerrod, rå",false),
                new Grocery("Skrubbe, rå",false),
                new Grocery("Skummetmælk, 0.1 % fedt",false),
                new Grocery("Skummetmælk, økologisk",false),
                new Grocery("Skummetmælkspulver",false),
                new Grocery("Skærekage, chokoladekage/-pie",false),
                new Grocery("Skærekage, formkage, uspec.",false),
                new Grocery("Skærekage, sandkage",false),
                new Grocery("Smelteost, 30+",false),
                new Grocery("Smør, saltet",false),
                new Grocery("Smørbart blandingsprodukt, 75% fedt",false),
                new Grocery("Smørbart blandingsprodukt, let, 57% fedt",false),
                new Grocery("Småkage, cookie (amerikansk type), industrifremstillet",false),
                new Grocery("Småkage, havreflager, industrifremstillet",false),
                new Grocery("Småkage, klejne, industrifremstillet",false),
                new Grocery("Småkage, med lavt sukkerindhold (sukkerfri, light) industrifremstillet",false),
                new Grocery("Småkage, uspec.",false),
                new Grocery("Snacks, ekspanderet, kartoffelbasis",false),
                new Grocery("Snacks, ekstruderet, majsbasis",false),
                new Grocery("Snaps, krydder-, uspec.",false),
                new Grocery("Sojabønner, tørrede, rå",false),
                new Grocery("Sojadrik, tilsat calcium",false),
                new Grocery("Sojaolie",false),
                new Grocery("Solbær, syltede",false),
                new Grocery("Solbærmarmelade",false),
                new Grocery("Solbærsaft, sød, koncentreret",false),
                new Grocery("Solsikkeolie",false),
                new Grocery("Sortmund, blåhvilling, filet, rå",false),
                new Grocery("Spegepølse, oksekød",false),
                new Grocery("Sperling, kød, rå",false),
                new Grocery("Spidskål, rå",false),
                new Grocery("Spinat, konserves",false),
                new Grocery("Spirituosa, gennemsnitlige værdier",false),
                new Grocery("Spædbørnsmad, modermælkserstatning, højt jernindhold, pulver",false),
                new Grocery("Spædbørnsmad, modermælkserstatning, lavt jernindhold, pulver",false),
                new Grocery("Squash, zucchini, rå",false),
                new Grocery("Stenbider, rå",false),
                new Grocery("Sukker, brun farin",false),
                new Grocery("Sukker, stødt melis (saccharose)",false),
                new Grocery("Surbrød",false),
                new Grocery("Sveske, rå",false),
                new Grocery("Syltetøj, uspec.",false),
                new Grocery("Sælkød, råt",false),
                new Grocery("Sødmælk, konventionel (ikke-økologisk)",false),
                new Grocery("Sødmælkspulver",false),
                new Grocery("Tahin, lys",false),
                new Grocery("Tang, agar, tørret",false),
                new Grocery("Te, blade",false),
                new Grocery("Tebirkes",false),
                new Grocery("Tidselolie",false),
                new Grocery("Tomat, dansk, rå",false),
                new Grocery("Tomat, importeret, rå",false),
                new Grocery("Tomat, uspec., rå",false),
                new Grocery("Tomatketchup",false),
                new Grocery("Tomatpure",false),
                new Grocery("Tomatsuppe, spiseklar",false),
                new Grocery("Torsk, filet, paneret, rå",false),
                new Grocery("Torsk, filet, rå",false),
                new Grocery("Torsk, lever, konserves",false),
                new Grocery("Torsk, lever, rå",false),
                new Grocery("Torsk, rogn, konserves",false),
                new Grocery("Torsk, rogn, rå",false),
                new Grocery("Trekantsandwich med kylling og bacon, salat og dressing, fastfood",false),
                new Grocery("Trekantsandwich med æg, salat og dressing, fastfood",false),
                new Grocery("Tun i tomat, konserves",false),
                new Grocery("Tun, gulfinnet, rå",false),
                new Grocery("Tunge, gris, rå",false),
                new Grocery("Tunge, kalv, rå",false),
                new Grocery("Tunge, okse, rå",false),
                new Grocery("Tvebakker",false),
                new Grocery("Tyggegummi, uden sukker, uspec.",false),
                new Grocery("Tyttebær, rå",false),
                new Grocery("Tørkage, kokosmakroner",false),
                new Grocery("Tørkage, linse",false),
                new Grocery("Tørkage, napoleonshatte",false),
                new Grocery("Vafler, blokvafler, blandede vafler, vaffelrør",false),
                new Grocery("Vallepulver, tørret",false),
                new Grocery("Valnøddeolie",false),
                new Grocery("Vandmelon, rå",false),
                new Grocery("Vekao",false),
                new Grocery("Vermouth, tør",false),
                new Grocery("Vindrue, rå",false),
                new Grocery("Vindruer, grønne (hvide), rå",false),
                new Grocery("Vodka",false),
                new Grocery("Voksbønner, rå",false),
                new Grocery("Whisky",false),
                new Grocery("Wienerbrød, kanelsnegl",false),
                new Grocery("Wienerbrød, smørkrans",false),
                new Grocery("Wienerbrød, uspec.",false),
                new Grocery("Wienerpølse, kogt, fastfood",false),
                new Grocery("Wienerpølse, ristet, fastfood",false),
                new Grocery("Yams, rå",false),
                new Grocery("Yderlår, skinkesteg, med svær, rå",false),
                new Grocery("Ymer naturel",false),
                new Grocery("Yoghurt med jordbær",false),
                new Grocery("Yoghurt med müsli",false),
                new Grocery("Yoghurt med pære og banan",false),
                new Grocery("Yoghurt naturel, 0.1 % fedt",false),
                new Grocery("Yoghurt naturel, sødmælk",false),
                new Grocery("Yoghurt, med frugt, 1.5 % fedt",false),
                new Grocery("Æble, dansk (sort: gråsten), råt",false),
                new Grocery("Æble, dansk (sort: stark earliest), råt",false),
                new Grocery("Æble, importeret, råt",false),
                new Grocery("Æble, uspec., råt",false),
                new Grocery("Æblemost, uspec.",false),
                new Grocery("Æg, blomme, tilsat sukker, pasteuriseret, dybfrost",false),
                new Grocery("Æg, høne, blomme, pasteuriseret",false),
                new Grocery("Æg, høne, blomme, saltet, pasteuriseret",false),
                new Grocery("Æg, høne, burhøns, rå",false),
                new Grocery("Æg, høne, kogt, dybfrost",false),
                new Grocery("Æg, høne, pasteuriseret",false),
                new Grocery("Æg, høne, røræg, industrifremstillet",false),
                new Grocery("Æg, høne, tørret",false),
                new Grocery("Æg, høne, æggehvide, rå",false),
                new Grocery("Æg, høne, økologisk drift, rå",false),
                new Grocery("Øl, Guld-, 5.6 % vol.",false),
                new Grocery("Øl, mørkt hvidtøl",false),
                new Grocery("Øl, skatteklasse 3, uspec.",false),
                new Grocery("Ørred, dam-, sø-, rå",false),
                new Grocery("Ørred, regnbue-, rå",false),
                new Grocery("Ål, røget",false)
        };
                //        List<Grocery> groceries = new ArrayList<>();
//        return groceries.toArray(new Grocery[groceries.size()]);
    }
}
